nginx/Dockerfile
nginx/instana-config.json
nginx/nginx.conf

The files from the nginx-opentracing project cannot be used any
more as they could become incompatible. So use a plain Ubuntu 18.04
Bionic image instead. Set up the official Nginx mainline repository
and install Nginx 1.17.6. Adapt the nginx image Dockerfile and the
Nginx config to run with output to stdout. Download the Instana
ngx_http_opentracing_module for Nginx 1.17.6 as well. Adapt the
service name to "nginxtracing_nginx" to unify it with the Docker
image name.

Rework for cpp-sensor 0.7.0 and nginx 1.17.6

---

README.md

Move the section about the "Nginx Binary Signature" to the
debugging section and add a note that we cannot support older
versions than 0.7.0 any more. Also add the case that a firewall
blocks the agent port 42699.

README: Add a debugging section

---

README.md

We prepared the required changes regarding upstream tag handling
in nginx-opentracing v0.9.0. Since libinstana_sensor version 0.6.0
we use that version internally. So add that information to the
released binaries and the release history sections.
Reported-by: @LutzLange

README: Add used nginx-opentracing version

---

README.md

Customers started to wonder about the 0.8.0-rc1 release. The new
release of release candidates is to simplify the work of Instana QA.
Those are not meant to be used by customers. So document the included
changes as a preview.

README: Update release notes for 0.8.0-rc1

---

nginx/instana-config.json

We introduced the new option with version 0.8.0. So show how it is
used by setting it to its default. Basically only less or equal to
0 is forbidden.

instana-config.json: Show max_buffered_spans option

---

binaries.md

Some spelling and punctuation is not correct. Then the NGINX Plus
links do not work. There are still links to .so files. The structure
is not correct as the compatnfo links belong to the NGINX official
repository as well. So address those issues.
For Amazon Linux 1/2018.03 there are no separate packages in the
NGINX official repository but the CentOS 6 packages are compatible.
So add that note.

binaries: Fix issues found during review

---

README.md
binaries.md

binaries.md: Adapt to version 1.0.1
Update all download links to version 1.0.1. Add NGINX 1.19.1,
OpenResty 1.17.8.1 and OpenResty 1.15.8.3. Drop the note claiming
that OpenResty 1.15.8.3 is not supported.
------------------
README: Update the release history for 1.0.1
------------------
binaries.md: Drop redirection from NGINX+ to NGINX OSS
Drop the redirect from NGINX Plus to NGINX OSS for faster selection
of the required binaries. Just duplicate the respective entries and
add the links to the NGINX Plus admin guide for the installation.

Release 1.0.1

---

README.md
binaries.md

binaries.md: Adapt to version 1.1.0
Update all download links to version 1.1.0.
----
README: Update the release history for 1.1.0
We've fixed the agent discovery if `/proc/$pid/sched` (`CONFIG_SCHED_DEBUG`) is not available. The connection to the Instana agent works in this case now but it takes more time until the agent finds the PID from the parent namespace as the Instana NGINX tracer cannot provide this information.

Release 1.1.0

---

binaries.md

This is basically just using the same binary signature as the package from Amazon Linux 1 main repo.

binaries.md: Add CentOS/RHEL 7 EPEL NGINX 1.16.1 link

---

binaries.md

Add NGINX 1.19.3..1.19.6 and OpenResty 1.19.3.1. Drop CentOS/RHEL 6.

binaries: Update to 01/2021

---

README.md
binaries.md

binaries: Update to tracer version 1.1.2
-------------
README: Update the release history for 1.1.2
Also update `nginx-opentracing` version to `v0.18.0` in documentation
and replace the deprecated example `agent_endpoint`.

Release 1.1.2

---

docker-compose.yml
nginx/Dockerfile
nginx/nginx.conf

Use Ubuntu 20.04 as the base and use NGINX 1.21.1. Align the NGINX
config with the Instana docs esp. regarding `stub_status` config.

nginx: Update image and NGINX version

---

README.md

Version 1.2.0 provides full support for authorization subrequests.
So show how to use them by adding the `log_subrequest` directive
to the config and adding a debugging section entry.

README: Show how to trace subrequests

---

README.md
binaries.md

binaries: Use tracer 1.3.0 release
vim command: %s/\/1\.2\.3\//\/1.3.0\//g
diff: git diff --word-diff-regex="[0-9]+\.[0-9]+\.[0-9]+"
------------
README: Update the release history for 1.3.0

Release 1.3.0

---

README.md
binaries.md
client-app/.dockerignore
client-app/Dockerfile
docker-compose.yml
nginx/Dockerfile
server-app/.dockerignore
server-app/Dockerfile

README: mention NGINX OpenTracing 0.22.1
-------------------
binaries: Replace tracer version 1.3.0 with 1.4.0
Vim command: :%s/\/1\.3\.0\//\/1.4.0\//gc
Diff: git diff --word-diff-regex="[0-9]+\.[0-9]+\.[0-9]+"
----------------------
binaries: Add NGINX 1.21.5 and 1.21.6
--------------
README: Document release 1.4.0
Also document release 1.3.1.
------------------------
Use multi-stage builds to simplify build command
Use multi-stage docker builds to get better reproducible
and simpler builds for client-app and server-app. Java is no
longer required on the host.
Also upgrade from NGINX 1.21.1 to 1.21.6 and fix the Ubuntu code
name used for the official NGINX Ubuntu repository.

Release 1.4.0

---

README.md

The technology preview referenced in the section about Ingress NGINX
is no longer the preferred approach to instrument Ingress NGINX.
The section now references the AutoTrace WebHook instead.
- [Kanbanize Card](https://instana.kanbanize.com/ctrl_board/57/cards/87573/details/)

doc: reference AutoTrace WebHook instead of tech preview

---

docker-compose.yml

Due to IBM policies, the Instana agent image may not be uploaded to DockerHub anymore. The image was still cached on my machine though. But for other users `docker-compose up` results in an error when pulling the image. The Instana agent images are uploaded to icr.io now.
So update the agent image config with the information from the Instana UI "Installing Instana Agents" -> "Docker".

docker-compose: Pull the Instana agent from icr.io

---

.gitignore
README.md
agent/com.instana.agent.main.sender.File.cfg
docker-compose.yml

- Modify docker-compose file to use a local Nginx module
- Modify docker-compose file to enable the debug of agent's spans
Improvements

docker-compose: add possibility for a local Nginx module.

---

README.md

[Jira Ticket](https://jsw.ibm.com/browse/INSTA-8308)
Update changelog with 1.9.1 notes:
* Bug fix: Upper-case for `Server-Timing` header
* New Feature: Add command "`opentracing_remove_duplication`", to enable
removal of duplicated `Server-Timing` headers in Nginx response.
Add to README the description of command "`opentracing_remove_duplication`" in the NGINX configuration section.
Compliance

Version 1.9.1 release notes

---

binaries.md

Add versions missing from official docs, update headlines, and replace tracer version. Used the file diff tool `meld` for this.
vim command to replace tracer version: `%s/\/1\.9\.1\//\/1.10.0\//g`

binaries: Sync with official docs

---

README.md

Often the network interfaces are not cleaned up properly. So always run `docker-compose down` first. The phases `build` and `up` can be combined. The build result is cached. This is fast. So use `docker-compose down && docker-compose up --build`.

README: Use better docker-compose commands

---

README.md

DOC: Announce the changes from cpp-sensor 1.11.0, significant for the end users.
 * Add support for NGINX 1.27.3
  * Add support for nginx-plus R33
  * Removed the agent header check for the `Server` header in the discovery response.
Compliance

README: Add 1.11.0 to release history
